<?php 

$isPartner= Mage::getModel('marketplace/userprofile')->isPartner();
$helper=Mage::helper('marketplace');
$customerid=Mage::getSingleton('customer/session')->getCustomerId();
$prices = $this->getProduct()->getPrices();

if($isPartner==1){?><br/><br/><br/>
    <form action="<?php echo $this->getUrl('loseller/marketplaceaccount/editapprovedbatch',array('productid'=>$this->getProduct()->getId())) ?>" enctype="multipart/form-data" method="post" id="form-customer-product-new">
        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
        <input type="hidden" name="attribute_set_id" id="attribute_set_id" value="<?php echo $this->getProduct()->getAttributeSetId();  ?>" />
        <input type="hidden" name="type_id" id="producttype" value="<?php echo $this->getProduct()->getTypeId()?>" />
        <input type="hidden"  name="wstoreids" id="wstoreids" value="<?php echo Mage::app()->getStore()->getStoreId(); ?>" title="wstoreids" class="" />
        <textarea name="description" class="input-text" style="display: none" id="" rows="1" cols="1" ><?php echo $this->getProduct()->getDescription()?></textarea>
        <textarea name="short_description" id="" rows="1" style="display: none" cols="1" class="input-text" ><?php echo $this->getProduct()->getShortDescription()?></textarea>
        <input type="hidden" value="<?php echo $this->getProduct()->getVisibility()?>" name="visibility"/>
        <input type="hidden" value="<?php echo $this->getProduct()->getTaxClassId()?>" name="tax_class_id"/>
        <input type="hidden" value="<?php echo $this->getProduct()->getCategory()?>" name="category"/>
        <input type="hidden" value="<?php echo $this->getProduct()->getCode()?>" name="code"/>
        <input type="hidden" value="<?php echo $this->getProduct()->getQty()?>" name="qty"/>
        <input type="hidden" value="<?php echo $this->getProduct()->getPresentation()?>" name="presentation"/>
        <input type="hidden" value="<?php echo $this->getProduct()->getGroupPresentation()?>" name="group_presentation"/>
        <input type="hidden" value="<?php echo $this->getProduct()->getLevel()?>" name="level"/>
        <input type="hidden" value="<?php echo $this->getProduct()->getStatus()?>" name="status"/>
        <input type="hidden" value="<?php echo $this->getProduct()->getExpirationDate()?>" name="expiration_date"/>
        <input type="hidden" value="<?php echo $this->getProduct()->getBatchNumber()?>" name="batch_number"/>
        <input type="hidden" value="1" name="stock_data[is_in_stock]"/>
        <input type="hidden" value="1" name="is_salable"/>
        <input type="hidden" value="<?php echo $this->getProduct()->getBatchParentProduct()?>" name="batch_parent_product"/>
        <input type="hidden" value="1" name="batch_warehouse"/>
        <input type="hidden" class="" name="batch_seller" value="<?php echo $customerid?>"/>
        <input name="sku" id="sku" type="hidden" value="<?php echo $this->getProduct()->getSku()?>"/>
        <input type="hidden" class="" name="name" id="name" value="<?php echo $this->getProduct()->getName()?>"/>
     
        <div class="form registration">
            <div class="button view-form" style="z-index:1111;position: absolute; right: 0px;">
                <input type="button" onclick="confirm('<?php echo $this->__("Are you sure you want to delete these batch?")?>')?location.href='<?php echo $this->getUrl('loseller/marketplaceaccount/deletebatch',array('id'=>$this->getProduct()->getId())) ?>':''" value="<?php echo $this->__('Delete')?>">
            </div>
            <div class="button view-form" style="z-index:1111;position: absolute; right: 150px;">
                <input type="button" onclick="viewEdit();" value="<?php echo $this->__('Edit Info')?>">
            </div>
            <div class="clearfix">
                <div class="half">
                    <div class="form_field"><span class="label"><?php echo $this->__("Batch (No)")?>:</span></div>
                    <div class="form_field"><?php echo $this->getProduct()->getBatchNumber()?></div>
                    <div class="form_field"><span class="label"><?php echo $this->__("Expiration date")?>:</span></div>
                    <div class="form_field"><?php list($date,$time) = explode(' ',$this->getProduct()->getExpirationDate()); echo $date?></div>
                    <div class="form clearfix">
                        <div class="form_field"><span class="label lh40"><?php echo $this->__("Analytical certificate")?>:</span></div>		
                        <div class=" documents ">
                            <div class="form_field">
                                    <a href="<?php echo $this->getProduct()->getBatchCertificate()?>"><?php echo $this->__('View Certificate')?></a>
                            </div>	
                        </div>
                    </div>
                </div>
                <div class="half">
                    <div class="form_field"><span class="label"><?php echo $this->__("Quantity of primary boxes")?>:</span></div>
                    <div class="form_field"><?php echo round($this->getProduct()->getStockQty(),0)?></div>
                    <span class="view-form">
                        <?php if($prices['private']): ?>
                            <div class="form_field ">
                                <span class="label"><?php echo $this->__("Sale for private sector")?></span>
                            </div>
                            <div class="form_field"><?php echo ((isset($prices['private']))?Mage::helper('core')->currency($prices['private'], true, false):'');?></div>
                        <?php endif; ?>
                        <?php if($prices['government']): ?>
                            <div class="form_field ">
                                <span class="label"><?php echo $this->__("Sale for government sector")?></span>
                            </div>		
                            <div class="form_field"><?php echo ((isset($prices['government']))?Mage::helper('core')->currency($prices['government'], true, false):"");?></div>
                        <?php endif; ?>
                    </span>
                    <span class="edit-form" style="display: none;">
                        <div class="form_field one_line">
                            <span class="label">
                                <input type="checkbox" name="private_price" id="checkbox" value="" <?php if(isset($prices['private'])):?> checked="checked" <?php endif;?>>
                                <label class="showFormTransparent" for="checkbox"><span class="checkSpan"></span><?php echo $this->__("Sale for private sector")?></label>
                            </span>	
                            <input type="text" class="price transparent <?php if(isset($prices['private'])):?> visible" required="<?php endif;?>" name='price[private]' value="<?php if(isset($prices['private'])): echo round($prices['private'],2); endif;?>" placeholder="<?php echo $this->__("Price")?>">
                        </div>
                        <div class="form_field one_line">
                            <span class="label">
                                <input type="checkbox" name="government_price" id="checkbox2" value="" <?php if(isset($prices['government'])):?> checked="checked" <?php endif;?>>
                                <label class="showFormTransparent" for="checkbox2"><span class="checkSpan"></span><?php echo $this->__("Sale for government sector")?></label>
                            </span>	
                            <input type="text"  class="price transparent <?php if(isset($prices['government'])):?> visible" required="<?php endif;?>" name="price[government]" value="<?php if(isset($prices['government'])): echo round($prices['government'],2); endif;?>" placeholder="<?php echo $this->__("Price")?>">
                        </div>	
                    </span>
                </div>						
            </div>					
        </div>
        <div class="hidden" style="display: block;">
            <div class="subtitle blue"><?php echo $this->__('Foto and characteristics')?></div>
            <hr>
            <?php 
                $images = array();    
                $_images = $this->getProduct()->getMediaGalleryImages()->getItems(); 
                $i = 0;
                $images = array_fill(1,7,new Varien_Object());
                foreach ($_images as $key=>$val) {
                    $file = $val->getFile();
                    $images[$file[1]] = $val;
                }
            ?>
            <?php if(count($images)>0): ?> 
            <?php $mainImage = array_shift($images)?>
            <?php else:?>
            <?php $mainImage=false;?>
            <?php endif;?>
            <?php $placeholder = $this->getSkinUrl(Mage::helper('catalog/image')->init(Mage::getModel('catalog/product'), 'image')->getPlaceholder()); ?>
            <span class="view-form">
                <div class="addFotos">
                    <div class="addFotos_main">
                        <img src="<?php echo ($mainImage->getUrl()?$mainImage->getUrl():$placeholder)?>">
                    </div>
                    <?php foreach($images as $image):?>
                    <div class="addFotos_small">
                        <img src="<?php echo ($image->getUrl()?$image->getUrl():$placeholder)?>">
                    </div>
                    <?php endforeach;?>
                </div>
            </span>
            <span class="edit-form" style="display: none;">
                <div class="addFotos">
                    <div class="addFotos_main">
                        <span class="del-img" sel="<?php echo $mainImage->getUrl()?1:0; ?>" path="<?php echo $mainImage->getPath(); ?>"></span>
                        <img title="<?php echo $this->__('Commercial picture')?>" id='image_main' alt="<?php echo $this->__('Commercial picture')?>" src="<?php echo ($mainImage->getUrl()?$mainImage->getUrl():$placeholder)?>">
                        <span class="addFotos_link">
                            <input id="image_main" type="file" accept="image/*" name="image[1]" onchange='imagePreview($("image_main"),event)'>
                            <?php 
                                $fileName = $mainImage?explode('/', $mainImage->getUrl()):array();
                            ?>
                            <input type="hidden" name="defaultimage" id="defaultimage" value="<?php echo array_pop($fileName)?>">
                            <span class="addFotos_link_name"><?php echo $this->__('Commercial picture')?></span>
                        </span>
                    </div>
                    
                    <div class="addFotos_small">
                        <?php if(count($images)>0): ?> 
                        <?php $image = array_shift($images)?>
                        <?php else:?>
                        <?php $image=false;?>
                        <?php endif;?>

                        <span class="del-img" sel="<?php echo $image->getUrl()?1:0; ?>" path="<?php echo $image->getPath(); ?>"></span>
                        <img title="<?php echo $this->__('Top picture')?>" id='image_top' alt="<?php echo $this->__('Top picture')?>" src="<?php echo ($image->getUrl()?$image->getUrl():$placeholder)?>">
                        <span class="addFotos_link">
                            <input type="file" accept="image/*" name="image[2]" onchange='imagePreview($("image_top"),event)'>
                            <span class="addFotos_link_name"><?php echo $this->__('Top picture')?></span>
                        </span>
                    </div>

                    <div class="addFotos_small">
                        <?php if(count($images)>0): ?> 
                        <?php $image = array_shift($images)?>
                        <?php else:?>
                        <?php $image=false;?>
                        <?php endif;?>
                        <span class="del-img" sel="<?php echo $image->getUrl()?1:0; ?>" path="<?php echo $image->getPath(); ?>"></span>
                        <img title="<?php echo $this->__('Bottom picture')?>" id='image_bottom' alt="<?php echo $this->__('Bottom picture')?>" src="<?php echo ($image->getUrl()?$image->getUrl():$placeholder)?>">
                        <span class="addFotos_link">
                            <input type="file" accept="image/*" name="image[3]" onchange='imagePreview($("image_bottom"),event)'>
                            <span class="addFotos_link_name"><?php echo $this->__('Bottom picture')?></span>
                        </span>
                    </div>

                    <div class="addFotos_small">
                        <?php if(count($images)>0): ?> 
                        <?php $image = array_shift($images)?>
                        <?php else:?>
                        <?php $image=false;?>
                        <?php endif;?>
                        <span class="del-img" sel="<?php echo $image->getUrl()?1:0; ?>" path="<?php echo $image->getPath(); ?>"></span>
                        <img title="<?php echo $this->__('Left picture')?>" id='image_left' alt="<?php echo $this->__('Left picture')?>" src="<?php echo ($image->getUrl()?$image->getUrl():$placeholder)?>">
                        <span class="addFotos_link">
                            <input type="file" accept="image/*" name="image[4]" onchange='imagePreview($("image_left"),event)'>
                            <span class="addFotos_link_name"><?php echo $this->__('Left picture')?></span>
                        </span>
                    </div>

                    <div class="addFotos_small">
                        <?php if(count($images)>0): ?> 
                        <?php $image = array_shift($images)?>
                        <?php else:?>
                        <?php $image=false;?>
                        <?php endif;?>
                        <span class="del-img" sel="<?php echo $image->getUrl()?1:0; ?>" path="<?php echo $image->getPath(); ?>"></span>
                        <img title="<?php echo $this->__('Right picture')?>" id='image_right' alt="<?php echo $this->__('Right picture')?>" src="<?php echo ($image->getUrl()?$image->getUrl():$placeholder)?>">
                        <span class="addFotos_link">
                            <input type="file" accept="image/*" name="image[5]" onchange='imagePreview($("image_right"),event)'>
                            <span class="addFotos_link_name"><?php echo $this->__('Right picture')?></span>
                        </span>
                    </div>

                    <div class="addFotos_small">
                        <?php if(count($images)>0): ?> 
                        <?php $image = array_shift($images)?>
                        <?php else:?>
                        <?php $image=false;?>
                        <?php endif;?>
                        <span class="del-img" sel="<?php echo $image->getUrl()?1:0; ?>" path="<?php echo $image->getPath(); ?>"></span>
                        <img alt="<?php echo $this->__('Front picture')?>" id='image_front' title="<?php echo $this->__('Front picture')?>" src="<?php echo ($image->getUrl()?$image->getUrl():$placeholder)?>">
                        <span class="addFotos_link">
                            <input type="file" accept="image/*" name="image[6]" onchange='imagePreview($("image_front"),event)'>
                            <span class="addFotos_link_name"><?php echo $this->__('Front picture')?></span>
                        </span>
                    </div>

                    <div class="addFotos_small">
                        <?php if(count($images)>0): ?> 
                        <?php $image = array_shift($images)?>
                        <?php else:?>
                        <?php $image=false;?>
                        <?php endif;?>
                        <span class="del-img" sel="<?php echo $image->getUrl()?1:0; ?>" path="<?php echo $image->getPath(); ?>"></span>
                        <img alt="<?php echo $this->__('Back picture')?>" id='image_back' title="<?php echo $this->__('Back picture')?>" src="<?php echo ($image->getUrl()?$image->getUrl():$placeholder)?>">
                        <span class="addFotos_link">
                            <input type="file" accept="image/*" name="image[7]" onchange='imagePreview($("image_back"),event)'>
                            <span class="addFotos_link_name"><?php echo $this->__('Back picture')?></span>
                        </span>
                    </div>
                </div>
            </span>

            <div class="form registration">
                <div class="clearfix">
                    <div class="half">
                        <span class="view-form">
                            <div class="form_field"><span class="label"><?php echo $this->__('Length')?>:</span></div>
                            <div class="form_field"><?php echo $this->getProduct()->getBatchLength()?></div>
                            <div class="form_field"><span class="label"><?php echo $this->__('Width')?>:</span></div>
                            <div class="form_field"><?php echo $this->getProduct()->getBatchWidth()?></div>
                        </span>
                        <span class='edit-form' style='display:none;'>
                            <div class="form_field"><span class="label"><span>*</span><?php echo $this->__('Length')?>:</span></div>
                            <div class="form_field"><input required="required" type="text" name="batch_length" value='<?php echo $this->getProduct()->getBatchLength()?>'></div>
                            <div class="form_field"><span class="label"><span>*</span><?php echo $this->__('Width')?>:</span></div>
                            <div class="form_field"><input required="required" type="text" name="batch_width" value='<?php echo $this->getProduct()->getBatchWidth()?>'></div>
                        </span>
                    </div>
                    <div class="half">
                        <span class="view-form">
                            <div class="form_field"><span class="label"><?php echo $this->__('Height')?>:</span></div>
                            <div class="form_field"><?php echo $this->getProduct()->getBatchHeight()?></div>
                            <div class="form_field"><span class="label"><?php echo $this->__('Weight')?><?php echo $this->__('(kg)')?>:</span></div>
                            <div class="form_field"><?php echo (string)$this->getProduct()->getWeight()?></div>
                        </span>
                        <span class='edit-form' style='display:none;'>
                            <div class="form_field"><span class="label"><span>*</span><?php echo $this->__('Height')?>:</span></div>
                            <div class="form_field"><input required="required" type="text" name="batch_height" value='<?php echo $this->getProduct()->getBatchHeight()?>'></div>
                            <div class="form_field"><span class="label"><span>*</span><?php echo $this->__('Weight')?><?php echo $this->__('(kg)')?>:</span></div>
                            <div class="form_field"><input required="required" type="text" name="weight" value='<?php echo (string)$this->getProduct()->getWeight()?>'></div>
                        </span>
                    </div>						
                </div>	
            </div>
        </div>
            
        <div class="page-title button edit-form" style="text-align: center; display: none;">
            <div class="form">
                <div class="button">
                    <input type="submit" class="mp_delete" value="<?php echo $this->__('Save batch')?>">
                </div>
            </div>
        </div>
        
    </form>
    <script type="text/javascript"> 
    var $wk_jq=jQuery.noConflict();
    function imagePreview(image,event) {
        var allowedExt = ['jpg','gif','jpeg','png'];
        if($wk_jq(image).attr('id')=='image_main'){
            $wk_jq('#defaultimage').val(event.target.files[0].name);
        }
        var filename = event.target.files[0].name;
        var ext = filename.split('.').pop();
        if($wk_jq.inArray(ext.toLowerCase(),allowedExt)<0) {
            alert('<?php echo $this->__('Please select image')?>');
            $wk_jq(event.target).val('');
            return ;
        }
        $wk_jq('#'+$wk_jq(image).attr('id')+'_changed').val('1');
        image.src = URL.createObjectURL(event.target.files[0]);
        $wk_jq(image.previous(".del-img")).show();
    }

    $wk_jq(".del-img").on("click",function(){
        $wk_jq(this).next("img").attr("src", "<?php echo $this->getSkinUrl('img/addFotos.png')?>");
        $wk_jq(this).next("img").next(".addFotos_link").find("input").val("");
        $wk_jq(this).hide();

        $wk_jq.ajax({
            url: "<?php echo $this->getUrl('loseller/marketplaceaccount/deleteimage',array("_secure"=>true))?>",
            global: false,
            type: "POST",
            data: ({path : $wk_jq(this).attr('path'), id: '<?php echo $customerid; ?>',product_id:'<?php echo $this->getProduct()->getId();?>'}),
            dataType: "html",
            success: function(msg){
                console.log(msg);
            }
        });
    });
   
    function viewEdit() {
        $wk_jq('.view-form').hide();
        $wk_jq('.edit-form').show();
        $wk_jq('.del-img').each(function(){
            if($wk_jq(this).attr("sel") == 1){
                $wk_jq(this).show();
            }
        });
    }
    
    $wk_jq('#checkbox').change(addCheckinPrice);
    $wk_jq('#checkbox2').change(addCheckinPrice);
    
    function addCheckinPrice() {
        $wk_jq('.price').each(function(){
            $wk_jq(this).prop('required',false);
        })
        $wk_jq('.price').each(function(){
            if($wk_jq(this).hasClass('visible')) {
                $wk_jq(this).prop('required',true);
            }
        });
       if(!$wk_jq('.price').hasClass('visible')) {
           $wk_jq('.price').first().prop('required',true);
           $wk_jq('.price').first().val('');
       }
    }
    </script>
<?php }?>