<?php
$isPartner= Mage::getModel('marketplace/userprofile')->isPartner();
$helper= Mage::helper('marketplace');
if($isPartner==1){

    ?>

<?php
if(count($this->getCollection())==0){ ?>
    <div class="fieldset wk_mp_fieldset">
        <div class="wk_emptymsg">
            <?php echo $helper->__('No Product Available') ?>
        </div>
    </div>
<?php
} else{ ?>
    <form action="<?php echo $this->getUrl('marketplace/marketplaceaccount/massdeletesellerpro'); ?>" method="post" id="formmassdelete" name="formmassdelete">
        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
        <ul id="itemContainer" style="min-height: 988px;">
            <?php

            $i = 0;
            foreach($this->getCollection() as $products){
                $i++;
                $productMediaConfig = Mage::getModel('catalog/product_media_config');
                $salesdetail=Mage::getModel('marketplace/saleslist')->getSalesdetail($products->getEntityId());
                ?>
                <li class="productItem <?php echo $class = ($i == count($this->getCollection()))? 'wk_last_tr':''?>">

                    <input type="hidden" class="hidden_id" value="<?php echo $products->getEntityId(); ?>" />
                    <div class="productItem_mpart">
                        <div class="productItem_img">
                            <a href="<?php echo $this->getUrl('seller/marketplaceaccount/viewproduct/search_name/'.$products->getEntityId());?>">
                                <img src="<?php echo Mage::helper('catalog/image')->init($products,'image')->resize(150);?>" class="image" />
                            </a>
                        </div>
                        <div class="productItem_name">
                            <a href="<?php echo $this->getUrl('seller/marketplaceaccount/viewproduct/search_name/'.$products->getEntityId());?>">
                                <?php echo $products->getName();?>
                            </a>
                        </div>
                    </div>

                    <div class="productItem_bpart">
                        <table class="productItem_values">
                            <tbody>
                                <tr>
                                    <td class="bold"><?php echo $helper->__("General name"); ?>:</td>
                                    <td>
                                        <?php
                                        echo $products->getData('generic_name_s');
                                        //$attribute= Mage::getModel('loseller/goverment_catalog')->load($products->getGenericName());
                                        //$attributeData = $attribute->getData();
                                        //echo $attributeData["generic_name"];
                                        ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="bold"><?php echo $helper->__("Description"); ?>:</td>
                                    <td>
                                        <?php
                                        echo $products->getData('description_s');
                                        //$attribute= Mage::getModel('loseller/goverment_catalog')->load($products->getDescriptionA());
                                        //$attributeData = $attribute->getData();
                                        //echo $attributeData["description"];
                                        ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="bold"><?php echo $helper->__("Presentation"); ?>:</td>
                                    <td>
                                        <?php
                                        echo $products->getData('presentation_s');
                                        //$attribute= Mage::getModel('loseller/goverment_catalog')->load($products->getPresentation());
                                       // $attributeData = $attribute->getData();
                                        //echo $attributeData["presentation"];
                                        ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="bold"><?php echo $helper->__("Concentration/Quantity"); ?>:</td>
                                    <td>
                                        <?php

                                        echo $products->getData('qty_s');
                                        //$attribute= Mage::getModel('loseller/goverment_catalog')->load($products->getQty());
                                        //$attributeData = $attribute->getData();
                                        //echo $attributeData["qty"];
                                        ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="bold"><?php echo $helper->__("Medical specialty"); ?>:</td>
                                    <td>
                                        <?php

                                        echo $products->getData('category_s');

                                        //$attribute= Mage::getModel('loseller/goverment_catalog')->load($products->getCategory());
                                        //$attributeData = $attribute->getData();
                                        //echo $attributeData["category"];
                                        ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="bold"><?php echo $helper->__("Basic frame ID"); ?>:</td>
                                    <td>
                                        <?php

                                        echo $products->getData('code_s');
                                        //$attribute= Mage::getModel('loseller/goverment_catalog')->load($products->getCode());
                                        //$attributeData = $attribute->getData();
                                        //echo $attributeData["code"];
                                        ?>
                                    </td>
                                </tr>


                            </tbody>
                        </table>
                    </div>
                    <div class="productItem_spart">
                        <div class="form">
                            <div class="button"><input type="button" class="mp_delete" data-type="<?php echo $products->getTypeId(); ?>"
                                                       value="<?php echo $helper->__("Delete"); ?>"></div>
                        </div>
                        <div class="form">
                            <div class="button"><input type="button" data-type="<?php echo $products->getTypeId(); ?>"
                                                       value="<?php echo $helper->__("Copy"); ?>"></div>
                        </div>
                    </div>
                </li>

            <?php }?>
        </ul>

        <ul class="pagination">
            <?php
            $count = $this->getCollection()->getFirstItem()->getCountAll();
            $currPage = $this->getCollection()->getFirstItem()->getCurrPage();
            if($count>1):
            for($i=1; $i<=$count;$i++):?>
                <li>
                    <div class="button mb5  <?php if($currPage == $i){echo ' active';}?>">
                        <a style="cursor: pointer;" class="pager_submit" url="<?php echo $this->getUrl('marketplace/marketplaceaccount/myproductslist/page/'.$i); ?>"><?php echo $i;?></a>
                    </div>
                </li>
            <?php endfor; endif;?>
        </ul>
    </form>

    <script>

        $j(".pager_submit").on("click",function(){
            var url = $j(this).attr("url");
            $j("#filter_form").attr("action",url);
            $j("#filter_form").submit();
        });

        var $wk_jq=jQuery.noConflict();
        var newCustomerProductForm1 = new VarienForm('formmassdelete', true);
        (function($wk_jq){
            $wk_jq('body').delegate('.mp_edit','click',function(){
                var id=$wk_jq(this).parents('.productItem').find('.hidden_id').val();
                var dicision=confirm('<?php echo $helper->__(" Are you sure you want to edit this product ? ")?>');
                if(dicision==true){
                    var $type_id=$wk_jq(this).attr('data-type');
                    if($type_id=='simple')
                        window.location = "<?php echo $this->getUrl('marketplace/marketplaceaccount/editapprovedsimple/') ?>".concat("id/",id);
                    if($type_id=='downloadable')
                        window.location = "<?php echo $this->getUrl('marketplace/marketplaceaccount/editapproveddownloadable/') ?>".concat("id/",id);
                    if($type_id=='virtual')
                        window.location = "<?php echo $this->getUrl('marketplace/marketplaceaccount/editapprovedvirtual/') ?>".concat("id/",id);
                    if($type_id=='configurable')
                        window.location = "<?php echo $this->getUrl('marketplace/marketplaceaccount/editapprovedconfigurable/') ?>".concat("id/",id);
                    if($type_id=='batch')
                        window.location = "<?php echo $this->getUrl('loseller/marketplaceaccount/editapprovedbatch/') ?>".concat("id/",id);
                    <?php
                    echo $this->getChildHtml('mpgrouped_productslist');
                    echo $this->getChildHtml('mpbundle_productslist');
                    ?>
                }
            });
            $wk_jq('#mass_delete_butn').click(function(e){
                var flag =0;
                $wk_jq('.mpcheckbox').each(function(){
                    if (this.checked == true){
                        flag =1;
                    }
                });
                if (flag == 0){
                    alert("<?php echo $helper->__(' No Checkbox is checked ') ?>");
                    return false;
                }
                else{
                    var dicisionapp=confirm('<?php echo $helper->__(" Are you sure you want to delete these product ? ")?>');
                    if(dicisionapp==true){
                        $wk_jq('#form-customer-product-new').submit();
                    }else{
                        return false;
                    }
                }
            });

            $wk_jq('#mpselecctall').click(function(event) {
                if(this.checked) {
                    $wk_jq('.mpcheckbox').each(function() {
                        this.checked = true;
                    });
                }else{
                    $wk_jq('.mpcheckbox').each(function() {
                        this.checked = false;
                    });
                }
            });

            $wk_jq('.mp_delete').click(function(){
                var id=$wk_jq(this).parents('.productItem').find('.hidden_id').val();
                var dicisionapp=confirm('<?php echo $helper->__(" Are you sure you want to delete this product ? ")?>');
                if(dicisionapp==true)
                    window.location = "<?php echo $this->getUrl('seller/marketplaceaccount/delete/') ?>".concat("id/",id);
            });
        })($wk_jq);
    </script>
<?php }?>
<?php
}else{
    echo "<h2 class='wk_new_msg'>".$helper->__("To BECOME SELLER PLEASE CONTACT TO ADMIN.")."</h2>";
}?>

