<?php
/**
 * 
 */
?>
<div class="form_field">
    <span class='label' for="<?php echo $this->getFieldId('firstname')?>"><span>*</span><?php echo $this->__('Contact name') ?></label></span>
</div>        
<div class="form_field">
    <input type="text" id="<?php echo $this->getFieldId('firstname')?>" name="<?php echo $this->__('firstname') ?>" value="<?php echo $this->escapeHtml($this->getObject()->getFirstname()) ?>" title="<?php echo $this->__('Contact name') ?>" maxlength="255" required="required" <?php echo $this->getFieldParams() ?> />
</div>


