<script>
if (typeof jQuery == 'undefined'){
    document.write(unescape("%3Cscript src='//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
}
</script>

<?php $_orders = $this->getOrders(); ?>
<?php echo $this->getMessagesBlock()->toHtml(); ?>

<div class="page-title">
    <h1><?php echo $this->__('My Orders') ?></h1>
</div>

<?php echo $this->getChildHtml('info');?>

<form action="<?php echo Mage::helper('core/url')->getCurrentUrl();?>" method="post">
    <table class="dealerActionsTbl">
        <colgroup>
            <col width="70">
            <col width="170">
            <col width="170">
            <col width="170">
            <col width="170">
            <col width="170">
            <col width="70">
        </colgroup>
        <thead>
            <tr>
                <th>
                    <div class="name"><?php echo $this->__('Order #') ?></div>
                    <input name="s" value="<?php echo $this->getRequest()->getParam('s'); ?>">
                </th>
                <th>
                    <div class="name"><?php echo $this->__('Purchased on') ?></div>
                    <div class="range">
                        <div class="dib mb10">
                            <?php echo $this->__('From:') ?>
                            <input name="from_date" id="special_from_date" value="<?php echo $this->getRequest()->getParam('from_date')?>">
                        </div>
                        <div class="dib">
                            <?php echo $this->__('To:') ?>
                            <input name="to_date" id="special_to_date" value="<?php echo $this->getRequest()->getParam('to_date')?>">
                        </div>
                    </div>
                </th>
                <th>
                    <div class="name"><?php echo $this->__('Total Price') ?></div>
                    <div class="range">
                        <div class="dib mb10">
                            <?php echo $this->__('From:') ?>
                            <input name="from_price" value="<?php echo $this->getRequest()->getParam('from_price')?>">
                        </div>
                        <div class="dib">
                            <?php echo $this->__('To:') ?>
                            <input name="to_price" value="<?php echo $this->getRequest()->getParam('to_price')?>">
                        </div>
                    </div>
                </th>
                <th>
                    <div class="name"><?php echo $this->__('Payment') ?></div>
                    <select name="payment">
                        <option value=""><?php echo $this->__('All') ?></option>
                        <?php foreach ($this->getPaymentMethods() as $_method): ?>
                            <option value="<?php echo $_method['id']; ?>" <?php if ($_method['id'] == $this->getRequest()->getParam('payment')): ?>selected<?php endif; ?>><?php echo $this->__($_method['name']); ?></option>
                        <?php endforeach; ?>
                    </select>
                </th>
                <th>
                    <div class="name"><?php echo $this->__('Company Seller') ?></div>
                    <select name="seller">
                        <option value=""><?php echo $this->__('All') ?></option>
                        <?php foreach ($this->getSellers($_orders) as $_seller): ?>
                        <option value="<?php echo htmlspecialchars($_seller['id']); ?>" <?php if ($_seller['id'] == $this->getRequest()->getParam('seller')): ?>selected<?php endif; ?>><?php echo  Mage::helper('loregistration')->__($_seller['name']); ?></option>
                        <?php endforeach; ?>
                    </select>
                </th>
                <th>
                    <div class="name"><?php echo $this->__('Order Status') ?></div>
                    <select name="status">
                        <option value=""><?php echo $this->__('All') ?></option>
                        <?php foreach ($this->getStatuses() as $_status): ?>
                            <option value="<?php echo $_status['id']; ?>" <?php if ($_status['id'] == $this->getRequest()->getParam('status')): ?>selected<?php endif; ?>><?php echo Mage::helper('loregistration')->__($_status['name']); ?></option>
                        <?php endforeach; ?>
                    </select>
                </th>
                <th class="dealerActions" style="vertical-align: middle;"><button type="submit" class="button"><?php echo $this->__('Submit'); ?></button></th>
            </tr>
        </thead>
        <tbody>
            <?php if ($_orders->getSize()): ?>
                <?php $_i = 0; foreach ($_orders as $_order): ?>
                    <tr style="cursor:pointer;" onclick="window.location.href='<?php echo $this->getUrl('marketplace/marketplaceaccount/viewbuyerorder',array('id'=>$_order->getId()))?>';" >
                        <td><?php echo $_order->getRealOrderId(); ?></td>
                        <td><?php echo $this->formatDate($_order->getCreatedAtStoreDate()); ?></td>
                        <td><?php echo $_order->formatPrice($_order->getGrandTotal()); ?></td>
                        <td><?php echo $this->__($_order->getPayment()->getMethodInstance()->getTitle()); ?></td>
                        <td><?php echo $_order->getSellerName(); ?></td>
                        <td><?php echo $_order->getStatusLabel(); ?></td>
                        <td>&nbsp;</td>
                    </tr>
                <?php $_i++; endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><?php echo $this->__('You have placed no orders.'); ?></td>
                </tr>
            <?php endif ?>
        </tbody>
    </table>
</form>

<script>
jQuery('document').ready(function() {
    jQuery( "#special_from_date" ).datetimepicker({lang:'<?php echo substr(Mage::app()->getLocale()->getLocaleCode(),0,2)?>',format: "Y-m-d", timepicker: false});
    jQuery( "#special_to_date" ).datetimepicker({lang:'<?php echo substr(Mage::app()->getLocale()->getLocaleCode(),0,2)?>',format: "Y-m-d", timepicker: false});
});
</script>
