<?php
$_order  = $this->getOrder();
$_seller = Mage::helper('buyerorders')->getSeller($_order)
?>

<h1><?php echo $this->__('Order #%s', $_order->getRealOrderId()) ?></h1>
<p><?php echo $this->__('Seller'); ?>: <?php echo $_seller->getFirstname() . ' (' . $_seller->getCompany() . ')'; ?></p>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<div class="col2-set">
    <?php if (!$_order->getIsVirtual()): ?>
    <div class="col-1">
        <h2><?php echo $this->__('Shipping Address') ?></h2>
        <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
    </div>
    <div class="col-2">
    <?php else: ?>
    <div class="col-1">
    <?php endif; ?>
        <h2><?php echo $this->__('Billing Address') ?></h2>
        <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
    </div>
<?php if (!$_order->getIsVirtual()): ?>
</div>
<div class="col2-set">
    <div class="col-1">
        <h2><?php echo $this->__('Shipping Method') ?></h2>
         <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>

        <div class="box">
            <div class="box-title"><h2><?php echo $this->__('Tracking'); ?></h2></div>
            <div class="box-content">
                <?php if ($_tracking = Mage::helper('buyerorders')->getTracking($_order)): ?>
                    <?php foreach ($_tracking as $_index => $_track): ?>
                        <?php $_index++; ?>
                        <div class="wk_row">
                            <span class="label"><?php echo $this->__('Tracking Number'); ?>: </span>
                            <span class="value"><?php echo $_track->getNumber(); ?></span>
                        </div>
                    <?php endforeach; ?>
                <?php else: ?>
                    <div class="wk_row">
                        <span class="label"><?php echo $_order->getStatusLabel(); ?></span>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
    <div class="col-2">
        <h2><?php echo $this->__('Payment Method') ?></h2>
        <?php echo $this->getPaymentInfoHtml() ?>
    </div>
</div>
<h2><?php echo $this->__('Items Ordered') ?></h2>
<table class="data-table" id="my-orders-table">
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th class="a-right"><?php echo $this->__('Price') ?></th>
            <th class="a-center"><?php echo $this->__('Qty') ?></th>
            <th class="a-right"><?php echo $this->__('Subtotal') ?></th>
        </tr>
    </thead>
    <tfoot>
        <?php echo $this->getChildHtml('order_totals') ?>
    </tfoot>
    <?php $_items = $_order->getItemsCollection(); ?>
    <?php $_count = $_items->count(); ?>
    <?php foreach ($_items as $_item): ?>
    <?php if ($_item->getParentItem()) continue; ?>
    <tbody>
        <?php echo $this->getItemHtml($_item) ?>
    </tbody>
        <?php endforeach; ?>
</table>
<script type="text/javascript">decorateTable('my-orders-table', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
<script type="text/javascript">window.print();</script>
