
<!--
<div class="button mb20"><a href="seller-add-product.html">Agregar nuevo producto</a></div>
<div class="subtitle">Especialidad</div>
<ul class="leftMenu">
    <li class="active">
        <a href="#">Grupo Nº1: Analgesia</a>
        <ul style="display: block;">
            <li><a href="#">Acido Acetilsalicico</a></li>
            <li><a href="#">Metamizol Sodico</a></li>
            <li><a href="#">Paracetamol</a></li>
            <li><a href="#">Buprenorfina</a></li>
            <li><a href="#">Capsaicina</a></li>
            <li><a href="#">Clonixinato de lisina</a></li>
            <li><a href="#">Dexmedetomidina</a></li>
        </ul>
    </li>
    <li class="">
        <a href="#">Grupo Nº3: Cardiología</a>
        <ul style="display: none;">
            <li><a href="#">Acido Acetilsalicico</a></li>
            <li><a href="#">Metamizol Sodico</a></li>
            <li><a href="#">Paracetamol</a></li>
        </ul>
    </li>
    <li class="">
        <a href="#">Grupo Nº4: Dermatología</a>
        <ul style="display: none;">
            <li><a href="#">Acido Acetilsalicico</a></li>
            <li><a href="#">Metamizol Sodico</a></li>
            <li><a href="#">Paracetamol</a></li>
            <li><a href="#">Buprenorfina</a></li>
        </ul>
    </li>
    <li class="">
        <a href="#">Grupo Nº5: Endocrinología y Metabolismo</a>
        <ul style="display: none;">
            <li><a href="#">Acido Acetilsalicico</a></li>
            <li><a href="#">Metamizol Sodico</a></li>
        </ul>
    </li>
</ul>
<div class="menuCheck">
    <input value="" id="checkbox" name="check" type="checkbox">
    <label for="checkbox"><span class="checkSpan"></span>Para su venta al sector gobierno</label>
</div>
<div class="menuCheck">
    <input value="" id="checkbox2" name="check" type="checkbox">
    <label for="checkbox2"><span class="checkSpan"></span>Para su venta al sector privado</label>
</div>
<div class="form">
    <div class="search form_field">
        <input placeholder="Buscar..." type="text"><span></span>
    </div>
</div>
-->

