<?php 
$isPartner= Mage::getModel('marketplace/userprofile')->isPartner(); 
$helper= Mage::helper('marketplace');
if($isPartner==1){
	?>
	<script type="text/javascript">
	if (typeof jQuery == 'undefined'){
	    document.write(unescape("%3Cscript src='//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
	}
	</script>
	<script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
	<link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
	<div class="page-title">
		<h1 style="float:left;"><?php echo $helper->__('List of orders') ?></h1>
	</div>
		<div class="wk_mp_design">
			<div class="fieldset">
				<div class="grid">
					<div class="hor-scroll">
                        <form action="<?php echo Mage::helper('core/url')->getCurrentUrl();?>" method="post">
                            <table class="dealerActionsTbl">
                                <colgroup>
                                    <col width="70">
                                    <col width="170">
                                    <col width="170">
                                    <col width="170">
                                    <col width="170">
                                    <col width="170">
                                    <col width="70">
                                </colgroup>
                                <thead>
                                    <tr class="headings">
                                        <th>
                                            <div class="name"><?php echo $this->__('Order #') ?></div>
                                            <input name="s" value="<?php echo $this->getRequest()->getParam('s'); ?>">
                                        </th>
                                        <th>
                                            <div class="name"><?php echo $this->__('Purchased') ?></div>
                                            <div class="range">
                                                <div class="dib mb10">
                                                    <?php echo $this->__('From:') ?>
                                                    <input name="from_date" id="special_from_date" value="<?php echo $this->getRequest()->getParam('from_date')?>">
                                                </div>
                                                <div class="dib">
                                                    <?php echo $this->__('To:') ?>
                                                    <input name="to_date" id="special_to_date" value="<?php echo $this->getRequest()->getParam('to_date')?>">
                                                </div>
                                            </div>
                                        </th>
                                        <th>
                                            <div class="name"><?php echo $this->__('Total Price') ?></div>
                                            <div class="range">
                                                <div class="dib mb10">
                                                    <?php echo $this->__('From:') ?>
                                                    <input name="from_price" value="<?php echo $this->getRequest()->getParam('from_price')?>">
                                                </div>
                                                <div class="dib">
                                                    <?php echo $this->__('To:') ?>
                                                    <input name="to_price" value="<?php echo $this->getRequest()->getParam('to_price')?>">
                                                </div>
                                            </div>
                                        </th>
                                        <th>
                                            <div class="name"><?php echo $this->__('Payment') ?></div>
                                            <?php
                                                $payments = Mage::getSingleton('payment/config')->getActiveMethods();
                                                $methods  = array(array('value' => '', 'label' => Mage::helper('adminhtml')->__('All')));
                                                foreach ($payments as $paymentCode => $paymentModel) {
                                                    $paymentTitle          = Mage::getStoreConfig('payment/'.$paymentCode.'/title');
                                                    $methods[$paymentCode] = array(
                                                        'label' => $this->__($paymentTitle),
                                                        'value' => $paymentCode,
                                                    );
                                                }
                                            ?>
                                            <select name="payment">
                                                <?php foreach ($methods as $method): ?>
                                                    <option value="<?php echo $method['value']; ?>" <?php if ($method['value'] == $this->getRequest()->getParam('payment')): ?>selected<?php endif; ?>><?php echo $method['label']; ?></option>
                                                <?php endforeach; ?>
                                            </select>
                                        </th>
                                        <th>
                                            <div class="name"><?php echo $this->__('Buyer name') ?></div>
                                            <select name="buyer">
                                                <option value=""><?php echo $helper->__('All') ?></option>
                                                <?php foreach ($this->getBuyers() as $buyer): ?>
                                                    <option value="<?php echo htmlspecialchars($buyer['id']); ?>" <?php if ($buyer['id'] == $this->getRequest()->getParam('buyer')): ?>selected<?php endif; ?>><?php echo $buyer['name']; ?></option>
                                                <?php endforeach; ?>
                                            </select>
                                        </th>
                                        <th>
                                            <div class="name"><?php echo $this->__('Order Status') ?></div>
                                            <select name="orderstatus">
                                                <option value=""><?php echo $helper->__('All') ?></option>
                                                <?php
                                                foreach ($this->getStatuses() as $orderstatus) {
                                                    ?>
                                                    <option value="<?php echo $orderstatus['id']?>" <?php if($this->getRequest()->getParam('orderstatus') == $orderstatus['id']) echo 'selected="selected"'?>>
                                                        <?php echo Mage::helper('loregistration')->__($orderstatus['name']); ?>
                                                    </option>
                                                    <?php
                                                }
                                                ?>
                                            </select>
                                        </th>
                                        <th class="dealerActions" style="vertical-align: middle;"><button type="submit" class="button"><?php echo $this->__('Submit'); ?></button></th>
                                    </tr>
                                </thead>

						<?php 
						if(!$this->getCollection()->getSize()){ ?>		
                            <tr>
                                <td colspan="7"><?php echo $helper->__('No Order Available') ?></td>
                            </tr>
							<?php 
						} else{ ?>
                                <tbody>

							<?php $i=0;
							foreach($this->getCollection() as $res){
								$order = Mage::getModel('sales/order')->load($res['mageorderid']);
								$status=$order->getStatus();
								$name=$order->getCustomerName();
                                $payment = $order->getPayment()->getMethodInstance()->getTitle();
								if($res['mageorderid']>0){
									$i++;?>

                                    <tr style="cursor: pointer;" onclick="window.location.href='<?php echo $this->getUrl('marketplace/marketplaceaccount/vieworder',array('id'=>$res['mageorderid']))?>'">
                                        <td><?php echo $res['magerealorderid']; ?></td>
                                        <td><?php echo $this->formatDate($res->getClearedAt()) ?></td>
                                        <td><?php echo Mage::helper('core')->currency(Mage::getModel('marketplace/saleslist')->getPricebyorder($res['mageorderid'])); ?></td>
                                        <td><?php echo $this->__($payment); ?></td>
                                        <td><?php echo $name; ?></td>
                                        <td><?php echo $helper->__($this->getStatus($order)); ?></td>
                                        <td>&nbsp;</td>
                                    </tr>
								<?php }
							} 	?>

                                </tbody>

							<?php
						}?>
                            </table>
                        </form>
					</div>
				</div>
			</div>	
			<div class="buttons-set"></div>
		</div>
		<script> 
		var $wk_jq=jQuery.noConflict();
		(function($wk_jq){
			$wk_jq( "#special_from_date" ).datetimepicker({lang:'<?php echo substr(Mage::app()->getLocale()->getLocaleCode(),0,2)?>',format: "Y-m-d", timepicker:false});
			$wk_jq( "#special_to_date" ).datetimepicker({lang:'<?php echo substr(Mage::app()->getLocale()->getLocaleCode(),0,2)?>',format: "Y-m-d", timepicker:false});			
		})($wk_jq);
		</script>
		<?php 
}else{
	echo "<h2 class='wk_new_msg'>".$helper->__("To BECOME SELLER PLEASE CONTACT TO ADMIN.")."</h2>";
}?>
