<div class="text multiple-checkout">
    <div class="form clearfix">
        <div class="page-title">
            <h1><?php echo $this->__('Review Order') ?></h1>
        </div>

        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

        <form id="review-order-form" action="<?php echo $this->getPostActionUrl() ?>" method="post" onsubmit="return showLoader();">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <div class="col-1">
                <h3 class="legend"><?php echo $this->__('Shipping Information') ?></h3>

                <?php foreach ($this->getShippingAddresses() as $_index => $_address): ?>
                    <?php if ($_index > 0): ?>
                        <?php continue; ?>
                    <?php endif; ?>

                    <div class="col-1">
                        <div class="box">
                            <div class="box-title" style="text-align:right;">
                                <h3><?php echo $this->__('Shipping Address') ?> <span class="separator">|</span> <a href="<?php echo $this->getEditShippingAddressUrl($_address) ?>"><?php echo $this->__('Change') ?></a></h3>
                            </div>
                            <div class="box-content">
                                <address>
                                    <?php echo $_address->format('html') ?>
                                </address>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>

            <div class="col-1">
                <h3 class="legend"><?php echo $this->__('Billing Information') ?></h3>
                <div class="col-1">
                    <div class="box">
                        <?php $_address=$this->getBillingAddress() ?>
                        <div class="box-title" style="text-align:right;">
                            <h3><?php echo $this->__('Billing Address') ?> <span class="separator">|</span> <a href="<?php echo $this->getEditBillingAddressUrl($_address) ?>"><?php echo $this->__('Change') ?></a></h3>
                        </div>
                        <div class="box-content">
                            <address>
                                <?php echo $_address->format('html') ?>
                            </address>
                        </div>
                    </div>
                </div>
                <div class="col-1">
                    <h3 class="legend"><?php echo $this->__('Payment Information') ?></h3>
                    <div class="box">
                        <div class="box-title" style="text-align:right;">
                            <h3><?php echo $this->__('Payment Method') ?> <span class="separator">|</span> <a href="<?php echo $this->getEditBillingUrl() ?>"><?php echo $this->__('Change') ?></a></h3>
                        </div>
                        <div class="box-content">
                            <input type="hidden" name="payment[cc_number]" value="<?php echo $this->escapeHtml($this->getPayment()->getCcNumber())?>" />
                            <input type="hidden" name="payment[cc_cid]" value="<?php echo $this->escapeHtml($this->getPayment()->getCcCid())?>" />
                            <?php echo $this->getPaymentHtml() ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col2-set">

                <?php foreach ($this->getShippingAddresses() as $_index => $_address): ?>
                    <h3><?php echo $this->__('Seller:') .' '. Mage::helper('buyercheckout')->getCompanyFromAddress($_address); ?></h3>

                    <div class="col-1 col-narrow">
                        <div class="box box-pad">
                            <div class="box-title">
                                <h4><?php echo $this->__('Shipping Method') ?> <span class="separator">|</span> <a href="<?php echo $this->getEditShippingUrl() ?>"><?php echo $this->__('Change') ?></a></h4>
                            </div>
                            <div class="box-content">
                                <?php if($_rate=$this->getShippingAddressRate($_address)): ?>
                                <p>
                                <?php echo $this->escapeHtml($_rate->getCarrierTitle()) ?> - <?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
                                <?php $_excl = $this->getShippingPriceExclTax($_address); ?>
                                <?php $_incl = $this->getShippingPriceInclTax($_address); ?>
                                <?php echo $_excl; ?>
                                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                <?php endif; ?>
                                </p>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>

                    <div class="col-2 col-wide">
                        <h4><?php echo $this->__('Items') ?></h4>

                        <?php $_tableClass = $this->helper('tax')->displayCartBothPrices() ? 'linearize-table-large' : 'linearize-table'; ?>
                        <table class="data-table <?php echo $_tableClass; ?> checkout-review-table table" id="overview-table-<?php echo $_address->getId() ?>">
                            <col width="1" />
                            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                            <col width="1" />
                            <?php endif; ?>
                            <col width="1" />
                            <col width="1" />
                            <col width="1" />
                            <col width="1" />
                            <col width="1" />
                            <col width="1" />
                            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                            <col width="1" />
                            <?php endif; ?>
                            <thead>
                                <tr>
                                    <th rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Batch #') ?></th>
                                    <th colspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Product Name') ?></th>
                                    <th rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Expiration Date') ?></th>
                                    <th colspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
                                    <th rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Presentation') ?></th>
                                    <th rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Price') ?></th>
                                    <th colspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Ordered qty') ?></th>
                                    <th colspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Subtotal') ?></th>
                                </tr>
                                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                                <tr>
                                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                                </tr>
                                <?php endif; ?>
                            </thead>
                            <tfoot>
                                <?php echo $this->renderTotals($this->getShippingAddressTotals($_address)); ?>
                            </tfoot>
                            <tbody>
                                <tr>
                                <?php foreach ($this->getShippingAddressItems($_address) as $_item): ?>
                                    <?php echo $this->getRowItemHtml($_item); ?>
                                <?php endforeach; ?>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <?php if($this->getShippingAddressCount()!=$_index+1): ?>
                        <div class="divider"></div>
                    <?php endif; ?>
                <?php endforeach; ?>


               <?php echo $this->getChildHtml('items_after'); ?>
            </div>

            <div id="checkout-review-submit">
                <?php echo $this->getChildHtml('agreements') ?>
                <div class="place-order">
                    <div class="grand-total">
                        <div class="inner">
                            <big><?php echo $this->__('Grand Total:') ?> <?php echo $this->helper('checkout')->formatPrice($this->getTotal()) ?></big>
                            <div id="review-buttons-container">
                                <button type="submit" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout" id="review-button"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
                            </div>
                        </div>
                        <span class="please-wait" id="review-please-wait" style="display:none;">
                            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
                        </span>
                    </div>
                </div>
            </div>

            <div class="buttons-set">
                <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Billing Information') ?></a></p>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    var submitted = false;

    function showLoader()
    {
        if (submitted) {
            return false;
        }
        if ($('checkout-agreements')) {
            var checkboxes = $$('#checkout-agreements input');
            for (var i=0, l=checkboxes.length; i<l; i++) {
                if (!checkboxes[i].checked) {
                    alert("<?php echo $this->__('Please agree to all Terms and Conditions before placing the orders.')?>");
                    return false;
                }
            }
        }

        submitted = true;
        var step='review';
        Element.show(step+'-please-wait');
        $(step+'-buttons-container').setStyle({opacity:.5});
        $(step+'-buttons-container').descendants().each(function(s) {
              s.disabled = true;
        });
        return true;
    }
</script>
