<div id="body" class="courier_font">
<ul class="bxslider">
<li><img title="<span><span>Desafiamos </span>las reglas<br> del mercado</span>" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>slider/slide_1.jpg" /></li>
<li><img title="<span><span>Regresamos </span> al origen</span>" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>slider/slide_2.jpg"></li>
<li><img title="<span><span>¡PENSAMOS MEJOR!, </span> ¡PENSAMOS DIFERENTE!</span>" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>slider/slide_3.jpg" /></li>
<li><img title="<span><span>El tiempo está </span> en tus manos</span>" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>slider/slide_4.jpg" /></li>
<!-- <li><img title="<span><span>El tiempo está </span> en tus manos</span>" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>slider/12-1440h.jpg" /></li>
<li><img title="<span><span>El tiempo está </span> en tus manos</span>" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>slider/23-1440h.jpg" /></li>
<li><img title="<span><span>El tiempo está </span> en tus manos</span>" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>slider/34-1440h.jpg" /></li>
<li><img title="<span><span>El tiempo está </span> en tus manos</span>" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>slider/56-1440h.jpg" /></li>
<li><img title="<span><span>El tiempo está </span> en tus manos</span>" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>slider/67-1440h.jpg" /></li>
<li><img title="<span><span>El tiempo está </span> en tus manos</span>" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>slider/slide14.jpg" /></li>
<li><img title="<span><span>El tiempo está </span> en tus manos</span>" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>slider/slide15.jpg" /></li>
<li><img title="<span><span>El tiempo está </span> en tus manos</span>" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>slider/slide16.jpg" /></li>
<li><img title="<span><span>El tiempo está </span> en tus manos</span>" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>slider/slide17.jpg" /></li>
<li><img title="<span><span>El tiempo está </span> en tus manos</span>" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>slider/slide18.jpg" /></li>
<li><img title="<span><span>El tiempo está </span> en tus manos</span>" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>slider/slide19.jpg" /></li> -->
</ul>
<div class="text info_blockTbl">
<div class="info_block_title info_block_left">nuestros clientes</div>
<div class="info_block_text">
<p>Nuestros clientes, al igual que nosotros, aman la libertad de elecci&oacute;n y la eficiencia. Es por ello que a trav&eacute;s de contar con una gran variedad de productos, condiciones de libre competencia y distintas opciones de env&iacute;o, MedicJoint ofrece un ambiente donde el elegir libremente, conseguir las mejores condiciones de precio y obtener productos de forma inmediata es cosa de todos los d&iacute;as.</p>
<p>Para garantizar la libertad de elecci&oacute;n, en MedicJoint compartimos la informaci&oacute;n del mercado de medicamentos de forma transparente y clara. De este modo, nuestros clientes optimizan sus compras de forma simple y r&aacute;pida al tomar decisiones libres, racionales e informadas.</p>
</div>
</div>
<div class="title">conozcan m&aacute;s</div>
<div class="servicesBlocks">
    <div class="servicesBlocks_item products"><a href="<?php echo $this->getUrl('catalog.html')?>"><span>Extensa gama de productos</span></a></div>
<div class="servicesBlocks_item statistics"><a href="<?php echo (!Mage::getSingleton('customer/session')->isLoggedIn()?$this->getUrl('statistics'):"#")?>"><span>Pron&oacute;sticos estad&iacute;sticos</span></a></div>
<div class="servicesBlocks_item prices"><a href="<?php echo $this->getUrl('catalog.html')?>"><span>Mejores precios</span></a></div>
<div class="servicesBlocks_item offer"><a href="<?php echo $this->getUrl('catalog.html')?>"><span>Vende f&aacute;cilmente</span></a></div>
<div class="servicesBlocks_item delivery"><a href="<?php echo $this->getUrl('catalog.html')?>"><span>Entrega inmediata</span></a></div>
</div>
<div class="title">nuestros socios comerciales</div>
<p class="text tac">Nuestros socios comerciales comparten nuestra creencia de que el valor m&aacute;ximo de nuestra industria es la vida. Por ello, enfrentan d&iacute;a a d&iacute;a el gran desaf&iacute;o de desarrollar nuevos medicamentos, agregar valor a sus productos, ofrecer beneficios econ&oacute;micos y junto a nosotros ofrecer el mercado de medicamentos m&aacute;s eficiente para que sean nuestros clientes finales, en la b&uacute;squeda de salud y calidad de vida, quienes reciban los beneficios de tan ardua labor.</p>
<hr />
<ul class="clients_list justified">
	<li class="clients-1"><span>company name </span></li>
	<li class="clients-2"><span>company name </span></li>
	<li class="clients-3"><span>company name </span></li>
	<li class="clients-4"><span>company name </span></li>
	<li class="clients-5"><span>company name </span></li>
	<li class="clients-6"><span>company name </span></li>
</ul>
<?php if(!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
<div class="button mt30 mb30 tac"><a href="<?php echo $this->getUrl('customer/account/create')?>">reg&iacute;strese ahora</a></div>
<?php endif;?>
</div>