<?php $_order = $this->getOrder() ?>

<a href="<?php echo $this->getPrintUrl($_order) ?>" class="link-print" onclick="this.target='_blank';"><?php echo $this->__('Print') ?></a>

<?php if ('complete' !== $_order->getStatus()): ?>
    <span class="separator">|</span>
    <a href="<?php echo $this->getUrl('sales/order/receive', array('id' => $_order->getId())); ?>"><?php echo $this->__('I received this order') ?></a>
<?php endif; ?>

<?php echo $this->getChildHtml(); ?>

